// vim: ts=8 sw=8 noexpandtab
//
// This file serves as a source of examples to be embedded into
// the documentation generated by godoc.
//
// Please consult the appropriate source file and/or godoc page
// for more documentation relevant to the example.

package servers

import (
	"fmt"
	"github.com/racker/gorax/v2.0/identity"
)

const (
	USERNAME = "example.user"
	APIKEY   = "example.api.key"
)

func ExampleRegionByName() {
	id := identity.NewIdentity(USERNAME, APIKEY, "")
	err := id.Authenticate()
	if err != nil {
		panic(err)
	}

	region, err := RegionByName(id, "dfw")
	if err != nil {
		panic(err)
	}

	images, err := region.Images()
	if err != nil {
		panic(err)
	}

	fmt.Printf("%20s  Name\n", "UUID")
	for _, i := range images {
		fmt.Printf("%20s  %s\n", string(i.Id[0:20]), i.Name)
	}
}
